# Server Port
server.port=${PORT:8080}

# H2 Database Configurations
spring.datasource.url=jdbc:h2:mem:smartcare_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL Auto (creates tables on startup)
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console in Browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Security Properties
smartcare.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smartcare.jwt.expiration-ms=86400000
